FROM python:3.11.5

WORKDIR /inmuebles

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["bash", "-c", "python", "manage.py", "runserver", "-b", "0.0.0.0"]
