# Generated by Django 3.2.8 on 2023-09-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='pais',
            field=models.CharField(max_length=150),
        ),
    ]
